# inherits settings from https://github.com/Manjaro-Sway/.github/blob/main/.github/settings.yml
_extends: manjaro-contrib/.github
repository:
  homepage: https://aur.archlinux.org/pacseek.git
  topics: arch, package, x86-64, aarch64
# you can extend settings using https://probot.github.io/apps/settings/
