name: set version to src version

on:
  repository_dispatch:
    types:
      - source_update

concurrency: 
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: check out the repo
        id: checkout_repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          token: ${{ secrets.DISPATCH_TOKEN }}
      - name: update pkgbuild
        env:
          VERSION: ${{ github.event.client_payload.version }}
          MD5: ${{ github.event.client_payload.md5 }}
        run: |
          [ -n "$VERSION" ] && sed -i "/pkgver=/c\pkgver=${VERSION}" PKGBUILD || exit 0
          [ -n "$MD5" ] && sed -i "/_sourcemd5=/c\_sourcemd5=${MD5}" PKGBUILD || exit 0
      - name: commit
        run: |
          git config --global user.name "Repo Update Bot"
          git config --global user.email "info@manjaro-sway.download"
          git add PKGBUILD
          git commit -m "chore: release version ${{ github.event.client_payload.version }}"
          git push
